services:
  node-backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/frontend
      
  barista-staff-backend:
    build: ./Barista-Food-Staff/backend
    ports:
      - "3001:3001"
    volumes:
      - ./Barista-Food-Staff/frontend:/usr/src/frontend